// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockManagement.Model;

#nullable disable

namespace StockManagement.Migrations
{
    [DbContext(typeof(StockDBContext))]
    [Migration("20230905180630_Ice-CreamDB")]
    partial class IceCreamDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("StockManagement.Model.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompanyId");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("StockManagement.Model.Gari1", b =>
                {
                    b.Property<int>("Gari1Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Gari1Id"), 1L, 1);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Receive")
                        .HasColumnType("int");

                    b.Property<int>("Return")
                        .HasColumnType("int");

                    b.Property<int>("Sales")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Gari1Id");

                    b.HasIndex("ProductId");

                    b.ToTable("gari1");
                });

            modelBuilder.Entity("StockManagement.Model.Gari2", b =>
                {
                    b.Property<int>("Gari2Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Gari2Id"), 1L, 1);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Receive")
                        .HasColumnType("int");

                    b.Property<int>("Return")
                        .HasColumnType("int");

                    b.Property<int>("Sales")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Gari2Id");

                    b.HasIndex("ProductId");

                    b.ToTable("gari2");
                });

            modelBuilder.Entity("StockManagement.Model.Gari3", b =>
                {
                    b.Property<int>("Gari3Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Gari3Id"), 1L, 1);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Receive")
                        .HasColumnType("int");

                    b.Property<int>("Return")
                        .HasColumnType("int");

                    b.Property<int>("Sales")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Gari3Id");

                    b.HasIndex("ProductId");

                    b.ToTable("gari3");
                });

            modelBuilder.Entity("StockManagement.Model.IglooIceCream", b =>
                {
                    b.Property<int>("IglooIceCreamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IglooIceCreamId"), 1L, 1);

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Dumping")
                        .HasColumnType("int");

                    b.Property<int?>("Eja")
                        .HasColumnType("int");

                    b.Property<int?>("NewProduct")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("Receive")
                        .HasColumnType("int");

                    b.Property<int?>("Remaining")
                        .HasColumnType("int");

                    b.Property<int?>("SalesQuantity")
                        .HasColumnType("int");

                    b.Property<int?>("Total")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IglooIceCreamId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ProductId");

                    b.ToTable("iglooIceCreams");
                });

            modelBuilder.Entity("StockManagement.Model.KaziFarmFood", b =>
                {
                    b.Property<int>("KaziFarmFoodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KaziFarmFoodId"), 1L, 1);

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Dumping")
                        .HasColumnType("int");

                    b.Property<int?>("Eja")
                        .HasColumnType("int");

                    b.Property<int?>("NewProduct")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("Receive")
                        .HasColumnType("int");

                    b.Property<int?>("Remaining")
                        .HasColumnType("int");

                    b.Property<int?>("SalesQuantity")
                        .HasColumnType("int");

                    b.Property<int?>("Total")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("KaziFarmFoodId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ProductId");

                    b.ToTable("kaziFarmFoods");
                });

            modelBuilder.Entity("StockManagement.Model.LovelloIceCream", b =>
                {
                    b.Property<int>("LovelloIceCreamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LovelloIceCreamId"), 1L, 1);

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Dumping")
                        .HasColumnType("int");

                    b.Property<int?>("Eja")
                        .HasColumnType("int");

                    b.Property<int?>("NewProduct")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("Receive")
                        .HasColumnType("int");

                    b.Property<int?>("Remaining")
                        .HasColumnType("int");

                    b.Property<int?>("SalesQuantity")
                        .HasColumnType("int");

                    b.Property<int?>("Total")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("LovelloIceCreamId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ProductId");

                    b.ToTable("lovelloIceCreams");
                });

            modelBuilder.Entity("StockManagement.Model.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"), 1L, 1);

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("IsActive")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.HasIndex("CompanyId");

                    b.ToTable("products");
                });

            modelBuilder.Entity("StockManagement.Model.RoleMaster", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"), 1L, 1);

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("RoleMaster");
                });

            modelBuilder.Entity("StockManagement.Model.SavoyIceCream", b =>
                {
                    b.Property<int>("SavoyIceCreamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SavoyIceCreamId"), 1L, 1);

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Dumping")
                        .HasColumnType("int");

                    b.Property<int?>("Eja")
                        .HasColumnType("int");

                    b.Property<int?>("NewProduct")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("Receive")
                        .HasColumnType("int");

                    b.Property<int?>("Remaining")
                        .HasColumnType("int");

                    b.Property<int?>("SalesQuantity")
                        .HasColumnType("int");

                    b.Property<int?>("Total")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SavoyIceCreamId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ProductId");

                    b.ToTable("savoyIceCreams");
                });

            modelBuilder.Entity("StockManagement.Model.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("StockManagement.Model.ZaNZeeIceCream", b =>
                {
                    b.Property<int>("ZaNZeeIceCreamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ZaNZeeIceCreamId"), 1L, 1);

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Dumping")
                        .HasColumnType("int");

                    b.Property<int?>("Eja")
                        .HasColumnType("int");

                    b.Property<int?>("NewProduct")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("Receive")
                        .HasColumnType("int");

                    b.Property<int?>("Remaining")
                        .HasColumnType("int");

                    b.Property<int?>("SalesQuantity")
                        .HasColumnType("int");

                    b.Property<int?>("Total")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ZaNZeeIceCreamId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ProductId");

                    b.ToTable("zaNZeeIceCreams");
                });

            modelBuilder.Entity("StockManagement.Model.Gari1", b =>
                {
                    b.HasOne("StockManagement.Model.Product", "Product")
                        .WithMany("Gari1s")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("StockManagement.Model.Gari2", b =>
                {
                    b.HasOne("StockManagement.Model.Product", "Product")
                        .WithMany("Gari2s")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("StockManagement.Model.Gari3", b =>
                {
                    b.HasOne("StockManagement.Model.Product", "Product")
                        .WithMany("Gari3s")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("StockManagement.Model.IglooIceCream", b =>
                {
                    b.HasOne("StockManagement.Model.Company", "Company")
                        .WithMany("IglooIceCreams")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StockManagement.Model.Product", "Product")
                        .WithMany("IglooIceCreams")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("StockManagement.Model.KaziFarmFood", b =>
                {
                    b.HasOne("StockManagement.Model.Company", "Company")
                        .WithMany("KaziFarmFoods")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StockManagement.Model.Product", "Product")
                        .WithMany("KaziFarmFoods")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("StockManagement.Model.LovelloIceCream", b =>
                {
                    b.HasOne("StockManagement.Model.Company", "Company")
                        .WithMany("LovelloIceCreams")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StockManagement.Model.Product", "Product")
                        .WithMany("LovelloIceCreams")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("StockManagement.Model.Product", b =>
                {
                    b.HasOne("StockManagement.Model.Company", "Company")
                        .WithMany("Products")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("StockManagement.Model.SavoyIceCream", b =>
                {
                    b.HasOne("StockManagement.Model.Company", "Company")
                        .WithMany("SavoyIceCreams")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StockManagement.Model.Product", "Product")
                        .WithMany("SavoyIceCreams")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("StockManagement.Model.User", b =>
                {
                    b.HasOne("StockManagement.Model.RoleMaster", "RoleMaster")
                        .WithMany("Users")
                        .HasForeignKey("RoleId");

                    b.Navigation("RoleMaster");
                });

            modelBuilder.Entity("StockManagement.Model.ZaNZeeIceCream", b =>
                {
                    b.HasOne("StockManagement.Model.Company", "Company")
                        .WithMany("ZaNZeeIceCreams")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StockManagement.Model.Product", "Product")
                        .WithMany("ZaNZeeIceCreams")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("StockManagement.Model.Company", b =>
                {
                    b.Navigation("IglooIceCreams");

                    b.Navigation("KaziFarmFoods");

                    b.Navigation("LovelloIceCreams");

                    b.Navigation("Products");

                    b.Navigation("SavoyIceCreams");

                    b.Navigation("ZaNZeeIceCreams");
                });

            modelBuilder.Entity("StockManagement.Model.Product", b =>
                {
                    b.Navigation("Gari1s");

                    b.Navigation("Gari2s");

                    b.Navigation("Gari3s");

                    b.Navigation("IglooIceCreams");

                    b.Navigation("KaziFarmFoods");

                    b.Navigation("LovelloIceCreams");

                    b.Navigation("SavoyIceCreams");

                    b.Navigation("ZaNZeeIceCreams");
                });

            modelBuilder.Entity("StockManagement.Model.RoleMaster", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
